"""Research-only Operating Threshold Explorer.

Uses REAL, recomputed per-clip INT8 spoof scores on the frozen 200-clip
evaluation set (app/data/int8_evaluation_scores.json -- generated by
re-running the unmodified, frozen `predict()` path over the same
evaluation clips already used for the accepted metrics; verified to
reproduce those exact metrics at the production threshold before being
committed). This tool NEVER changes the production threshold
(candidate_e.INT8_DYNAMIC_CALIBRATED_THRESHOLD) -- it only recomputes
metrics at alternate, hypothetical thresholds over already-stored scores,
for educational/research purposes.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

_SCORES_PATH = Path(__file__).resolve().parents[1] / "data" / "int8_evaluation_scores.json"


def load_int8_evaluation_scores() -> dict | None:
    try:
        with _SCORES_PATH.open("r", encoding="utf-8") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return None


@dataclass
class ThresholdPoint:
    threshold: float
    fpr: float
    fnr: float
    balanced_accuracy: float
    accuracy: float


def sweep_thresholds(records: list[dict], thresholds: list[float]) -> list[ThresholdPoint]:
    """Pure metric recomputation over already-stored (spoof_score, label)
    pairs -- no model inference, no threshold change to production."""
    y_true = [1 if r["label"] == "spoof" else 0 for r in records]
    scores = [r["spoof_score"] for r in records]
    n = len(records)

    points = []
    for t in thresholds:
        tp = tn = fp = fn = 0
        for y, s in zip(y_true, scores):
            pred_spoof = s >= t
            if y == 1 and pred_spoof:
                tp += 1
            elif y == 0 and not pred_spoof:
                tn += 1
            elif y == 0 and pred_spoof:
                fp += 1
            else:
                fn += 1
        fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0
        fnr = fn / (fn + tp) if (fn + tp) > 0 else 0.0
        tpr = 1.0 - fnr
        tnr = 1.0 - fpr
        balanced_accuracy = (tpr + tnr) / 2.0
        accuracy = (tp + tn) / n if n > 0 else 0.0
        points.append(ThresholdPoint(threshold=t, fpr=fpr, fnr=fnr, balanced_accuracy=balanced_accuracy, accuracy=accuracy))
    return points
